// Generated by scripts/generate-resume-edit-operation-types.mjs.
// Edit the backend JSON Schema, then run pnpm generate:agent-contract.
import type { ResumeSection, ResumeSectionItem } from "@/types/resume";

export type ResumeEditOperation =
  {
    type: "replace_field";
    path: "basic.headline" | "basic.summary";
    value: string;
  }
  | {
    type: "insert_section";
    section: ResumeSection;
    index?: number;
  }
  | {
    type: "update_section";
    sectionId: string;
    patch: {
      title: string;
    };
  }
  | {
    type: "delete_section";
    sectionId: string;
  }
  | {
    type: "reorder_sections";
    sectionIds: string[];
  }
  | {
    type: "insert_item";
    sectionId: string;
    item: ResumeSectionItem;
    index?: number;
  }
  | {
    type: "update_item";
    sectionId: string;
    itemId: string;
    patch: {
      school?: string;
      degree?: string;
      major?: string;
      gpa?: string;
      location?: string;
      period?: string;
      company?: string;
      position?: string;
      name?: string;
      title?: string;
      authors?: string;
      venue?: string;
      role?: string;
      techStack?: string[];
      url?: string;
      issuer?: string;
      date?: string;
      description?: string;
      highlights?: string[];
      content?: string;
    };
  }
  | {
    type: "delete_item";
    sectionId: string;
    itemId: string;
  }
  | {
    type: "reorder_items";
    sectionId: string;
    itemIds: string[];
  };
