// Generated by scripts/generate-resume-edit-operation-types.mjs.
// Edit the backend JSON Schema, then run pnpm generate:agent-contract.
import type { ResumeSection, ResumeSectionItem } from "@/types/resume";

export type ResumeEditOperation =
  {
    type: "replace_field";
    path: "basic.headline" | "basic.location" | "basic.summary";
    value: string;
  }
  | {
    type: "insert_section";
    section: ResumeSection;
    index?: number;
  }
  | {
    type: "update_section";
    sectionId: string;
    patch: {
      kind?: ResumeSection["kind"];
      layout?: ResumeSection["layout"];
      customTitle?: string;
    };
  }
  | {
    type: "delete_section";
    sectionId: string;
  }
  | {
    type: "reorder_sections";
    sectionIds: string[];
  }
  | {
    type: "insert_item";
    sectionId: string;
    item: ResumeSectionItem;
    index?: number;
  }
  | {
    type: "update_item";
    sectionId: string;
    itemId: string;
    patch: {
      title?: string;
      subtitle?: string;
      meta?: string;
      period?: string;
      description?: string;
      highlights?: string[];
    };
  }
  | {
    type: "delete_item";
    sectionId: string;
    itemId: string;
  }
  | {
    type: "reorder_items";
    sectionId: string;
    itemIds: string[];
  };
