// Generated by scripts/generate-template-presets.mjs.
// Edit backend/app/services/template_presets.json, then run pnpm generate:template-presets.
export const builtinTemplatePresets = {
  "minimal": {
    "starter": "earlyCareer",
    "layout": {
      "basicInfo": "centered",
      "section": "ruled",
      "timelineItemLayout": "split",
      "sectionItemLayouts": {},
      "listItemLayout": "list",
      "avatarPosition": "right",
      "avatarShape": "rounded",
      "avatarWidth": 25,
      "avatarHeight": 32,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 0,
      "avatarBorderColor": "#e5e7eb",
      "images": []
    },
    "typography": {
      "fontFamily": "inter",
      "fontSize": 16
    },
    "settings": {
      "pagePaddingTop": 13,
      "pagePaddingX": 12,
      "pagePaddingBottom": 11,
      "sectionGap": 0.7,
      "itemGap": 0.88,
      "bodyLineHeight": 1.7,
      "nameScale": 2.15,
      "sectionTitleScale": 1.28,
      "itemTitleScale": 1.02,
      "metaScale": 0.92,
      "bodyScale": 0.96,
      "pageBackground": "#ffffff",
      "surfaceColor": "#f8fafc",
      "headingColor": "#000000",
      "bodyColor": "#000000",
      "mutedColor": "#525252",
      "dividerColor": "#202020",
      "dividerThickness": 1
    }
  },
  "modern": {
    "starter": "experienced",
    "layout": {
      "basicInfo": "profile",
      "section": "accent",
      "timelineItemLayout": "stacked",
      "sectionItemLayouts": {},
      "listItemLayout": "inline",
      "avatarPosition": "center",
      "avatarShape": "circle",
      "avatarWidth": 24,
      "avatarHeight": 24,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 2,
      "avatarBorderColor": "#ffffff",
      "images": []
    },
    "typography": {
      "fontFamily": "serif",
      "fontSize": 16
    },
    "settings": {
      "pagePaddingTop": 10,
      "pagePaddingX": 12,
      "pagePaddingBottom": 10,
      "sectionGap": 0.6,
      "itemGap": 0.62,
      "bodyLineHeight": 1.46,
      "nameScale": 1.98,
      "sectionTitleScale": 0.82,
      "itemTitleScale": 1.04,
      "metaScale": 0.92,
      "bodyScale": 0.95,
      "pageBackground": "#ffffff",
      "surfaceColor": "#f8fafc",
      "headingColor": "#2563eb",
      "bodyColor": "#000000",
      "mutedColor": "#525252",
      "dividerColor": "#3b82f6",
      "dividerThickness": 1
    }
  },
  "compact": {
    "starter": "experienced",
    "layout": {
      "basicInfo": "left",
      "section": "accent",
      "timelineItemLayout": "compact",
      "sectionItemLayouts": {},
      "listItemLayout": "columns",
      "avatarPosition": "right",
      "avatarShape": "square",
      "avatarWidth": 26,
      "avatarHeight": 32,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 0,
      "avatarBorderColor": "#ffffff",
      "images": []
    },
    "typography": {
      "fontFamily": "plex",
      "fontSize": 14
    },
    "settings": {
      "pagePaddingTop": 11,
      "pagePaddingX": 10,
      "pagePaddingBottom": 10,
      "sectionGap": 0.7,
      "itemGap": 0.82,
      "bodyLineHeight": 1.66,
      "nameScale": 1.9,
      "sectionTitleScale": 0.98,
      "itemTitleScale": 1,
      "metaScale": 0.9,
      "bodyScale": 0.94,
      "pageBackground": "#ffffff",
      "surfaceColor": "#be123c",
      "headingColor": "#be123c",
      "bodyColor": "#000000",
      "mutedColor": "#525252",
      "dividerColor": "#be123c",
      "dividerThickness": 1
    }
  },
  "classic": {
    "starter": "experienced",
    "layout": {
      "basicInfo": "left",
      "section": "ruled",
      "timelineItemLayout": "split",
      "sectionItemLayouts": {},
      "listItemLayout": "list",
      "avatarPosition": "right",
      "avatarShape": "rounded",
      "avatarWidth": 25,
      "avatarHeight": 32,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 0,
      "avatarBorderColor": "#d6d3d1",
      "images": []
    },
    "typography": {
      "fontFamily": "serif",
      "fontSize": 16
    },
    "settings": {
      "pagePaddingTop": 13,
      "pagePaddingX": 14,
      "pagePaddingBottom": 12,
      "sectionGap": 0.8,
      "itemGap": 0.78,
      "bodyLineHeight": 1.58,
      "nameScale": 2.05,
      "sectionTitleScale": 1.12,
      "itemTitleScale": 1.03,
      "metaScale": 0.9,
      "bodyScale": 0.95,
      "pageBackground": "#ffffff",
      "surfaceColor": "#f5f5f4",
      "headingColor": "#000000",
      "bodyColor": "#000000",
      "mutedColor": "#525252",
      "dividerColor": "#44403c",
      "dividerThickness": 1
    }
  },
  "executive": {
    "starter": "executive",
    "layout": {
      "basicInfo": "split",
      "section": "band",
      "timelineItemLayout": "compact",
      "sectionItemLayouts": {},
      "listItemLayout": "list",
      "avatarPosition": "right",
      "avatarShape": "square",
      "avatarWidth": 25,
      "avatarHeight": 32,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 0,
      "avatarBorderColor": "#cbd5e1",
      "images": []
    },
    "typography": {
      "fontFamily": "inter",
      "fontSize": 16
    },
    "settings": {
      "pagePaddingTop": 12,
      "pagePaddingX": 13,
      "pagePaddingBottom": 11,
      "sectionGap": 0.7,
      "itemGap": 0.68,
      "bodyLineHeight": 1.5,
      "nameScale": 2.2,
      "sectionTitleScale": 0.94,
      "itemTitleScale": 1.05,
      "metaScale": 0.92,
      "bodyScale": 0.94,
      "pageBackground": "#ffffff",
      "surfaceColor": "#e7f2f0",
      "headingColor": "#0f172a",
      "bodyColor": "#000000",
      "mutedColor": "#525252",
      "dividerColor": "#0f766e",
      "dividerThickness": 1.5
    }
  },
  "academic": {
    "starter": "research",
    "layout": {
      "basicInfo": "centered",
      "section": "underlined",
      "timelineItemLayout": "split",
      "sectionItemLayouts": {},
      "listItemLayout": "list",
      "avatarPosition": "none",
      "avatarShape": "rounded",
      "avatarWidth": 25,
      "avatarHeight": 32,
      "avatarOffsetX": 0,
      "avatarOffsetY": 0,
      "avatarBorderWidth": 0,
      "avatarBorderColor": "#d1d5db",
      "images": []
    },
    "typography": {
      "fontFamily": "times",
      "fontSize": 14
    },
    "settings": {
      "pagePaddingTop": 14,
      "pagePaddingX": 15,
      "pagePaddingBottom": 14,
      "sectionGap": 1.2,
      "itemGap": 0.4,
      "bodyLineHeight": 1.2,
      "nameScale": 1.6,
      "sectionTitleScale": 1,
      "itemTitleScale": 1,
      "metaScale": 1,
      "bodyScale": 1,
      "pageBackground": "#ffffff",
      "surfaceColor": "#f8fafc",
      "headingColor": "#000000",
      "bodyColor": "#000000",
      "mutedColor": "#000000",
      "dividerColor": "#000000",
      "dividerThickness": 1
    }
  }
} as const

export type GeneratedBuiltinTemplateId = keyof typeof builtinTemplatePresets
